### ISSUE TITLE
No icon with PR Sentiment Analyzer 1.0

### ISSUE THREAD

**Issue by grahamperrin** [olore/prs-a#1]
No icon when e.g. https://github.com/MrAlex94/Waterfox/pull/569 is viewed. 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.13_4
$ date ; uname -v
Fri 25 May 2018 18:50:52 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by olore** [comment]
Hi @grahamperrin! Thanks for the report. Looks like I missed an instruction or something.

I am seeing the icon, and it looks like you've got a "positive" comment :)

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/159987/40559027-5d9e1388-6023-11e8-8f77-64210cd5a811.png">

The plugin is configured to show on any URLs that matches ` "*://*.github.com/*/pull/*",` which this clearly does. Even if you haven't entered your host/key yet, I expect to see it. 

Do you have any errors in the console?

**Comment by olore** [comment]
Hi @grahamperrin Please let me know if this is still a problem in v1.2+ and either re-open or create another issue. Thanks again for trying this out!
